version: 0.2

env:
  variables:
    AWS_REGION: me-central-1
    ACCOUNT_ID: 767397902739
    IMAGE_REPO_NAME: node-docker-poc
    CLUSTER_NAME: node-app-ecs-cluster-musharraf
    SERVICE_NAME: node-app-musharraf-ecs-service
    TASK_FAMILY: node-app-musharraf

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=$COMMIT_HASH
      - IMAGE_URI=$ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG

      - echo Image tag will be $IMAGE_TAG

  build:
    commands:
      - echo Building Docker image...
      - docker build -t $IMAGE_URI .

  post_build:
    commands:
      - echo Pushing Docker image...
      - docker push $IMAGE_URI

      - echo Fetching current task definition
      - aws ecs describe-task-definition --task-definition $TASK_FAMILY --query taskDefinition > taskdef.json

      - echo Updating image in task definition
      - sed -i "s|IMAGE_TAG|$COMMIT_HASH|g" taskdef.json

      - echo Registering new task definition revision
      - aws ecs register-task-definition --cli-input-json file://taskdef.json

      - echo Updating ECS service with new image...
      - aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --task-definition $TASK_FAMILY
